# Generated by Django 3.0.3 on 2020-04-08 07:22

from django.db import migrations, models
import django.db.models.deletion
import userApi.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FollowingRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('introduce', models.TextField(blank=True, null=True)),
                ('join_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('favorite_food', models.CharField(max_length=200, null=True)),
                ('nickname', models.CharField(max_length=100, null=True)),
                ('member_type', models.IntegerField(blank=True, default=0, null=True)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to=userApi.models.profile_image_path)),
                ('followers', models.ManyToManyField(blank=True, through='userApi.FollowingRelation', to='userApi.User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='followingrelation',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_follower', to='userApi.User'),
        ),
        migrations.AddField(
            model_name='followingrelation',
            name='following',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_following', to='userApi.User'),
        ),
        migrations.AlterUniqueTogether(
            name='followingrelation',
            unique_together={('follower', 'following')},
        ),
    ]
